using System.Text;
using CreatorsForge.Foundry.Core.Projects;

namespace CreatorsForge.Foundry.Build;

public static class CphInlineBridgeGenerator
{
    public const string RelativeOutputPath = "bridge/CPHInline.cs";

    public static string Generate(FoundryCphInlineBridge bridge)
    {
        ArgumentNullException.ThrowIfNull(bridge);
        Validate(bridge);

        return $$"""
            // <auto-generated>
            // Generated by Creators Forge Foundry.
            // Changes will be overwritten by the next build.
            // Bridge contract: {{bridge.Contract}}
            // </auto-generated>

            #if EXTERNAL_EDITOR
            using Streamer.bot.Plugin.Interface;
            #endif

            #if EXTERNAL_EDITOR
            public sealed class CPHInline : CPHInlineBase
            #else
            public class CPHInline
            #endif
            {
            #if EXTERNAL_EDITOR
                public override bool Execute()
            #else
                public bool Execute()
            #endif
                {
                    return global::{{bridge.EntryType}}.{{bridge.EntryMethod}}(
                        args,
                        message => CPH.LogInfo(message));
                }
            }

            """;
    }

    public static Task WriteAsync(
        FoundryCphInlineBridge bridge,
        string destinationPath,
        CancellationToken cancellationToken)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(destinationPath);
        return File.WriteAllTextAsync(
            destinationPath,
            Generate(bridge),
            new UTF8Encoding(encoderShouldEmitUTF8Identifier: false),
            cancellationToken);
    }

    private static void Validate(FoundryCphInlineBridge bridge)
    {
        if (!string.Equals(
                bridge.Contract,
                FoundryCphInlineBridge.SupportedContract,
                StringComparison.Ordinal))
        {
            throw new ArgumentException("The bridge contract is not supported.", nameof(bridge));
        }

        var typeSegments = bridge.EntryType.Split('.');
        if (typeSegments.Length < 2 || typeSegments.Any(segment => !IsIdentifier(segment)))
        {
            throw new ArgumentException(
                "The bridge entry type is not a fully qualified C# type name.",
                nameof(bridge));
        }

        if (!IsIdentifier(bridge.EntryMethod))
        {
            throw new ArgumentException(
                "The bridge entry method is not a C# method name.",
                nameof(bridge));
        }
    }

    private static bool IsIdentifier(string value) =>
        value.Length > 0 &&
        !IsCSharpReservedKeyword(value) &&
        (char.IsAsciiLetter(value[0]) || value[0] == '_') &&
        value.Skip(1).All(character =>
            char.IsAsciiLetterOrDigit(character) || character == '_');

    private static bool IsCSharpReservedKeyword(string value) => value is
        "abstract" or "as" or "base" or "bool" or "break" or "byte" or "case" or
        "catch" or "char" or "checked" or "class" or "const" or "continue" or
        "decimal" or "default" or "delegate" or "do" or "double" or "else" or
        "enum" or "event" or "explicit" or "extern" or "false" or "finally" or
        "fixed" or "float" or "for" or "foreach" or "goto" or "if" or "implicit" or
        "in" or "int" or "interface" or "internal" or "is" or "lock" or "long" or
        "namespace" or "new" or "null" or "object" or "operator" or "out" or
        "override" or "params" or "private" or "protected" or "public" or
        "readonly" or "ref" or "return" or "sbyte" or "sealed" or "short" or
        "sizeof" or "stackalloc" or "static" or "string" or "struct" or "switch" or
        "this" or "throw" or "true" or "try" or "typeof" or "uint" or "ulong" or
        "unchecked" or "unsafe" or "ushort" or "using" or "virtual" or "void" or
        "volatile" or "while";
}
