using CreatorsForge.Foundry.Core.Projects;

namespace CreatorsForge.Foundry.Workspaces.Tests;

public sealed class ObsPluginTemplateServiceTests
{
    private static readonly FoundryObsPlugin Plugin = new()
    {
        Contract = FoundryObsPlugin.SdkContract,
        ModuleName = "template-tests",
        EntrySymbol = "foundry_obs_plugin_load",
        DisplayName = "Template Tests",
        Author = "Creators Forge",
        Description = "Template verification.",
        ApiVersion = FoundryObsPlugin.SupportedSdkVersion,
        SdkVersion = FoundryObsPlugin.SupportedSdkVersion,
    };

    [Fact]
    public void CatalogueContainsFiveVersionedTemplates()
    {
        Assert.Equal(5, ObsPluginTemplateService.Templates.Count);
        Assert.Equal(
            FoundryObsDesign.SupportedTemplates.Order(StringComparer.Ordinal),
            ObsPluginTemplateService.Templates.Select(item => item.Id).Order(StringComparer.Ordinal));
    }

    [Theory]
    [InlineData(FoundryObsDesign.ModuleStarterTemplate, null)]
    [InlineData(FoundryObsDesign.PassthroughFilterTemplate, "OBS_SOURCE_TYPE_FILTER")]
    [InlineData(FoundryObsDesign.ConfigurableFilterTemplate, "obs_properties_add_bool")]
    [InlineData(FoundryObsDesign.VideoInputTemplate, "OBS_SOURCE_TYPE_INPUT")]
    [InlineData(FoundryObsDesign.OutputTemplate, "obs_register_output")]
    public void GenerationIsDeterministicAndUsesExpectedContract(
        string template,
        string? expectedText)
    {
        var design = CreateDesign(template);

        var first = ObsPluginTemplateService.Generate(Plugin, design);
        var second = ObsPluginTemplateService.Generate(Plugin, design);

        Assert.True(first.IsSuccess);
        Assert.Equal(first.Source, second.Source);
        Assert.StartsWith("/* Generated by Creators Forge Foundry.", first.Source, StringComparison.Ordinal);
        Assert.Contains("#include <obs-module.h>", first.Source, StringComparison.Ordinal);
        Assert.Contains("bool foundry_obs_plugin_load(void)", first.Source, StringComparison.Ordinal);
        if (expectedText is not null)
        {
            Assert.Contains(expectedText, first.Source, StringComparison.Ordinal);
        }
    }

    [Fact]
    public void GenerationEscapesUserVisibleNameAndCreatesPortableSymbols()
    {
        var result = ObsPluginTemplateService.Generate(
            Plugin,
            CreateDesign(FoundryObsDesign.PassthroughFilterTemplate) with
            {
                ComponentId = "dev.creator.my-filter",
                ComponentName = "Creator's \"Filter\"",
            });

        Assert.True(result.IsSuccess);
        Assert.Contains("foundry_dev_creator_my_filter_info", result.Source, StringComparison.Ordinal);
        Assert.Contains("Creator's \\\"Filter\\\"", result.Source, StringComparison.Ordinal);
    }

    [Theory]
    [InlineData(FoundryObsDesign.PassthroughFilterTemplate)]
    [InlineData(FoundryObsDesign.ConfigurableFilterTemplate)]
    [InlineData(FoundryObsDesign.VideoInputTemplate)]
    [InlineData(FoundryObsDesign.OutputTemplate)]
    public void SourceTemplatesOwnAndDestroyTheirPrivateContext(string template)
    {
        var result = ObsPluginTemplateService.Generate(Plugin, CreateDesign(template));

        Assert.True(result.IsSuccess);
        Assert.Contains("bzalloc(sizeof(*context))", result.Source, StringComparison.Ordinal);
        Assert.Contains("bfree(data);", result.Source, StringComparison.Ordinal);
        Assert.Contains(".destroy = foundry_dev_creatorsforge_template_test_destroy,", result.Source, StringComparison.Ordinal);
    }

    [Fact]
    public void InvalidDesignIsRejectedBeforeRendering()
    {
        var result = ObsPluginTemplateService.Generate(
            Plugin,
            CreateDesign("unsupported") with
            {
                ComponentId = "Invalid ID",
                ComponentName = " ",
                Source = "plugin.txt",
            });

        Assert.False(result.IsSuccess);
        Assert.Null(result.Source);
        Assert.Equal(4, result.Errors.Count);
    }

    private static FoundryObsDesign CreateDesign(string template) => new()
    {
        Template = template,
        Source = "src/plugin.c",
        ComponentId = "dev.creatorsforge.template-test",
        ComponentName = "Template Test",
    };
}
