// <auto-generated>
// Generated by Creators Forge Foundry.
// Changes will be overwritten by the next build.
// Bridge contract: args-log-v1
// </auto-generated>

#if EXTERNAL_EDITOR
using Streamer.bot.Plugin.Interface;
#endif

#if EXTERNAL_EDITOR
public sealed class CPHInline : CPHInlineBase
#else
public class CPHInline
#endif
{
#if EXTERNAL_EDITOR
    public override bool Execute()
#else
    public bool Execute()
#endif
    {
        return global::CreatorsForge.Tests.Extension.EntryPoint.Execute(
            args,
            message => CPH.LogInfo(message));
    }
}
