<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Secondary assembly used to prove Streamer.bot dependency resolution.</Description>
    <ImplicitUsings>disable</ImplicitUsings>
    <LangVersion>7.3</LangVersion>
    <Nullable>disable</Nullable>
    <TargetFramework>net481</TargetFramework>
    <VersionPrefix>0.1.0</VersionPrefix>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference
      Include="Microsoft.NETFramework.ReferenceAssemblies"
      Version="1.0.3"
      PrivateAssets="all" />
  </ItemGroup>
</Project>
