<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <AssemblyName>CreatorsForge.Foundry</AssemblyName>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Assets\CreatorForgeLogo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AvalonEdit" Version="6.3.1.120" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\CreatorsForge.svg" />
    <Resource Include="Assets\CreatorForgeLogo.ico" />
    <Resource Include="Assets\Foundry.CFamily.Dark.xshd" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CreatorsForge.Foundry.Build\CreatorsForge.Foundry.Build.csproj" />
    <ProjectReference Include="..\CreatorsForge.Foundry.Core\CreatorsForge.Foundry.Core.csproj" />
    <ProjectReference Include="..\CreatorsForge.Foundry.Editor\CreatorsForge.Foundry.Editor.csproj" />
    <ProjectReference Include="..\CreatorsForge.Foundry.NativeTestHost\CreatorsForge.Foundry.NativeTestHost.csproj" />
    <ProjectReference Include="..\CreatorsForge.Foundry.Testing\CreatorsForge.Foundry.Testing.csproj" />
    <ProjectReference Include="..\CreatorsForge.Foundry.Workspaces\CreatorsForge.Foundry.Workspaces.csproj" />
  </ItemGroup>

</Project>
