using System.Text;
using CreatorsForge.Foundry.Core.Projects;

namespace CreatorsForge.Foundry.Workspaces;

public sealed record ObsPluginTemplateDescriptor(
    string Id,
    string Name,
    string Kind,
    string Description,
    string Result);

public sealed record ObsPluginTemplateResult(
    string? Source,
    IReadOnlyList<string> Errors)
{
    public bool IsSuccess => Source is not null && Errors.Count == 0;
}

public static class ObsPluginTemplateService
{
    public static IReadOnlyList<ObsPluginTemplateDescriptor> Templates { get; } =
    [
        new(
            FoundryObsDesign.ModuleStarterTemplate,
            "Module starter",
            "Module",
            "Smallest SDK-backed module entry point with an OBS log message.",
            "Loads successfully but does not register a source."),
        new(
            FoundryObsDesign.PassthroughFilterTemplate,
            "Passthrough video filter",
            "Filter",
            "Registers a synchronous video filter that forwards rendering unchanged.",
            "Appears under Effect Filters and is safe as a first functional plugin."),
        new(
            FoundryObsDesign.ConfigurableFilterTemplate,
            "Configurable video filter",
            "Filter",
            "Adds defaults and a Boolean property to the passthrough filter starter.",
            "Provides the settings callback structure for a real configurable effect."),
        new(
            FoundryObsDesign.VideoInputTemplate,
            "Video input source",
            "Input",
            "Registers a 1920x1080 synchronous video input source skeleton.",
            "Appears in Add Source and renders transparent output until drawing code is added."),
        new(
            FoundryObsDesign.OutputTemplate,
            "Encoded output",
            "Output",
            "Registers an encoded output with lifecycle-safe create, destroy, start, and stop callbacks.",
            "Provides a safe output-service skeleton for transport or recording implementations."),
    ];

    public static ObsPluginTemplateResult Generate(
        FoundryObsPlugin plugin,
        FoundryObsDesign design)
    {
        ArgumentNullException.ThrowIfNull(plugin);
        ArgumentNullException.ThrowIfNull(design);
        var errors = Validate(plugin, design);
        if (errors.Count != 0)
        {
            return new(null, errors);
        }

        var symbol = CreateCIdentifier(design.ComponentId);
        var source = design.Template switch
        {
            FoundryObsDesign.ModuleStarterTemplate => RenderModule(plugin, design),
            FoundryObsDesign.PassthroughFilterTemplate =>
                RenderFilter(plugin, design, symbol, configurable: false),
            FoundryObsDesign.ConfigurableFilterTemplate =>
                RenderFilter(plugin, design, symbol, configurable: true),
            FoundryObsDesign.VideoInputTemplate => RenderVideoInput(plugin, design, symbol),
            FoundryObsDesign.OutputTemplate => RenderOutput(plugin, design, symbol),
            _ => throw new InvalidOperationException("Template validation and rendering are out of sync."),
        };
        return new(NormalizeNewLines(source), []);
    }

    public static IReadOnlyList<string> Validate(
        FoundryObsPlugin plugin,
        FoundryObsDesign design)
    {
        var errors = new List<string>();
        if (!FoundryObsDesign.SupportedTemplates.Contains(design.Template))
        {
            errors.Add("Choose a supported OBS template.");
        }

        if (string.IsNullOrWhiteSpace(design.ComponentName))
        {
            errors.Add("Component name is required.");
        }

        if (string.IsNullOrWhiteSpace(design.ComponentId) ||
            !design.ComponentId.All(character =>
                char.IsAsciiLetterOrDigit(character) || character is '.' or '_' or '-') ||
            !char.IsAsciiLetterOrDigit(design.ComponentId[0]) ||
            design.ComponentId.Any(char.IsUpper))
        {
            errors.Add("Component ID must use lowercase letters, digits, dots, hyphens, or underscores.");
        }

        if (string.IsNullOrWhiteSpace(plugin.EntrySymbol))
        {
            errors.Add("Module entry symbol is required.");
        }

        if (!design.Source.EndsWith(".c", StringComparison.OrdinalIgnoreCase))
        {
            errors.Add("Generated source must use a .c file.");
        }

        return errors;
    }

    private static string RenderModule(FoundryObsPlugin plugin, FoundryObsDesign design) => $$"""
        /* Generated by Creators Forge Foundry. Template: {{design.Template}} */
        #include <obs-module.h>

        bool {{plugin.EntrySymbol}}(void)
        {
            blog(LOG_INFO, "[Creators Forge] {{EscapeCString(design.ComponentName)}} module loaded.");
            return true;
        }
        """;

    private static string RenderFilter(
        FoundryObsPlugin plugin,
        FoundryObsDesign design,
        string symbol,
        bool configurable)
    {
        var settingsCallbacks = configurable
            ? $$"""

              static void {{symbol}}_defaults(obs_data_t *settings)
              {
                  obs_data_set_default_bool(settings, "enabled", true);
              }

              static obs_properties_t *{{symbol}}_properties(void *data)
              {
                  UNUSED_PARAMETER(data);
                  obs_properties_t *properties = obs_properties_create();
                  obs_properties_add_bool(properties, "enabled", "Enabled");
                  return properties;
              }
              """
            : string.Empty;
        var infoSettings = configurable
            ? $$"""
                  .get_defaults = {{symbol}}_defaults,
                  .get_properties = {{symbol}}_properties,
              """
            : string.Empty;
        return $$"""
            /* Generated by Creators Forge Foundry. Template: {{design.Template}} */
            #include <obs-module.h>

            #define {{CreateMacroIdentifier(symbol)}}_ID "{{EscapeCString(design.ComponentId)}}"

            static const char *{{symbol}}_name(void *unused)
            {
                UNUSED_PARAMETER(unused);
                return "{{EscapeCString(design.ComponentName)}}";
            }

            struct {{symbol}}_context {
                obs_source_t *source;
            };

            static void *{{symbol}}_create(obs_data_t *settings, obs_source_t *source)
            {
                UNUSED_PARAMETER(settings);
                struct {{symbol}}_context *context = bzalloc(sizeof(*context));
                context->source = source;
                return context;
            }

            static void {{symbol}}_destroy(void *data)
            {
                bfree(data);
            }

            static void {{symbol}}_render(void *data, gs_effect_t *effect)
            {
                UNUSED_PARAMETER(effect);
                struct {{symbol}}_context *context = data;
                obs_source_skip_video_filter(context->source);
            }
            {{settingsCallbacks}}

            static struct obs_source_info {{symbol}}_info = {
                .id = {{CreateMacroIdentifier(symbol)}}_ID,
                .type = OBS_SOURCE_TYPE_FILTER,
                .output_flags = OBS_SOURCE_VIDEO,
                .get_name = {{symbol}}_name,
                .create = {{symbol}}_create,
                .destroy = {{symbol}}_destroy,
                .video_render = {{symbol}}_render,
            {{infoSettings}}};

            bool {{plugin.EntrySymbol}}(void)
            {
                obs_register_source(&{{symbol}}_info);
                blog(LOG_INFO, "[Creators Forge] Registered {{EscapeCString(design.ComponentName)}}.");
                return true;
            }
            """;
    }

    private static string RenderVideoInput(
        FoundryObsPlugin plugin,
        FoundryObsDesign design,
        string symbol) => $$"""
        /* Generated by Creators Forge Foundry. Template: {{design.Template}} */
        #include <obs-module.h>

        #define {{CreateMacroIdentifier(symbol)}}_ID "{{EscapeCString(design.ComponentId)}}"

        static const char *{{symbol}}_name(void *unused)
        {
            UNUSED_PARAMETER(unused);
            return "{{EscapeCString(design.ComponentName)}}";
        }

        struct {{symbol}}_context {
            obs_source_t *source;
        };

        static void *{{symbol}}_create(obs_data_t *settings, obs_source_t *source)
        {
            UNUSED_PARAMETER(settings);
            struct {{symbol}}_context *context = bzalloc(sizeof(*context));
            context->source = source;
            return context;
        }

        static void {{symbol}}_destroy(void *data)
        {
            bfree(data);
        }

        static uint32_t {{symbol}}_width(void *data)
        {
            UNUSED_PARAMETER(data);
            return 1920;
        }

        static uint32_t {{symbol}}_height(void *data)
        {
            UNUSED_PARAMETER(data);
            return 1080;
        }

        static void {{symbol}}_render(void *data, gs_effect_t *effect)
        {
            UNUSED_PARAMETER(data);
            UNUSED_PARAMETER(effect);
            /* Add graphics rendering here. The starter intentionally renders transparent output. */
        }

        static struct obs_source_info {{symbol}}_info = {
            .id = {{CreateMacroIdentifier(symbol)}}_ID,
            .type = OBS_SOURCE_TYPE_INPUT,
            .output_flags = OBS_SOURCE_VIDEO,
            .get_name = {{symbol}}_name,
            .create = {{symbol}}_create,
            .destroy = {{symbol}}_destroy,
            .get_width = {{symbol}}_width,
            .get_height = {{symbol}}_height,
            .video_render = {{symbol}}_render,
        };

        bool {{plugin.EntrySymbol}}(void)
        {
            obs_register_source(&{{symbol}}_info);
            blog(LOG_INFO, "[Creators Forge] Registered {{EscapeCString(design.ComponentName)}}.");
            return true;
        }
        """;

    private static string RenderOutput(
        FoundryObsPlugin plugin,
        FoundryObsDesign design,
        string symbol) => $$"""
        /* Generated by Creators Forge Foundry. Template: {{design.Template}} */
        #include <obs-module.h>

        #define {{CreateMacroIdentifier(symbol)}}_ID "{{EscapeCString(design.ComponentId)}}"

        static const char *{{symbol}}_name(void *unused)
        {
            UNUSED_PARAMETER(unused);
            return "{{EscapeCString(design.ComponentName)}}";
        }

        struct {{symbol}}_context {
            obs_output_t *output;
        };

        static void *{{symbol}}_create(obs_data_t *settings, obs_output_t *output)
        {
            UNUSED_PARAMETER(settings);
            struct {{symbol}}_context *context = bzalloc(sizeof(*context));
            context->output = output;
            return context;
        }

        static void {{symbol}}_destroy(void *data)
        {
            bfree(data);
        }

        static bool {{symbol}}_start(void *data)
        {
            struct {{symbol}}_context *context = data;
            if (!obs_output_can_begin_data_capture(context->output, 0) ||
                !obs_output_initialize_encoders(context->output, 0)) {
                return false;
            }

            obs_output_begin_data_capture(context->output, 0);
            return true;
        }

        static void {{symbol}}_stop(void *data, uint64_t timestamp)
        {
            struct {{symbol}}_context *context = data;
            obs_output_end_data_capture(context->output);
            UNUSED_PARAMETER(timestamp);
        }

        static void {{symbol}}_encoded_packet(void *data, struct encoder_packet *packet)
        {
            UNUSED_PARAMETER(data);
            UNUSED_PARAMETER(packet);
            /* Send or persist encoded packets here. */
        }

        static struct obs_output_info {{symbol}}_info = {
            .id = {{CreateMacroIdentifier(symbol)}}_ID,
            .flags = OBS_OUTPUT_AV | OBS_OUTPUT_ENCODED,
            .get_name = {{symbol}}_name,
            .create = {{symbol}}_create,
            .destroy = {{symbol}}_destroy,
            .start = {{symbol}}_start,
            .stop = {{symbol}}_stop,
            .encoded_packet = {{symbol}}_encoded_packet,
        };

        bool {{plugin.EntrySymbol}}(void)
        {
            obs_register_output(&{{symbol}}_info);
            blog(LOG_INFO, "[Creators Forge] Registered {{EscapeCString(design.ComponentName)}}.");
            return true;
        }
        """;

    private static string CreateCIdentifier(string value)
    {
        var builder = new StringBuilder("foundry_");
        foreach (var character in value)
        {
            builder.Append(char.IsAsciiLetterOrDigit(character) ? character : '_');
        }

        return builder.ToString();
    }

    private static string CreateMacroIdentifier(string value) =>
        value.ToUpperInvariant();

    private static string EscapeCString(string value) => value
        .Replace("\\", "\\\\", StringComparison.Ordinal)
        .Replace("\"", "\\\"", StringComparison.Ordinal)
        .Replace("\r", "\\r", StringComparison.Ordinal)
        .Replace("\n", "\\n", StringComparison.Ordinal);

    private static string NormalizeNewLines(string value) =>
        value.Replace("\r\n", "\n", StringComparison.Ordinal).TrimEnd() + "\n";
}
